= Java 9 Worksop
:doctype: article
:encoding: utf-8
:lang: en
:force-include:

*Practice 1*

Create a "Hello world!" module. Compile, Run, Package and Link it.

1) Create the following structure.

[tree]
--
#hello
##src
###module-info.java
###com
####foo
#####Hello.java
--

.module-info.java
[source,java]
----
module com.foo {
    
}
----

[source,java]
----
package com.foo;

public class Hello {
    
    public static void main(String[] args) {
        
        System.out.println("Hello world!"); 
        
    }
    
}
----

2) Compile

[source,bash]
----
cd hello
javac src/module-info.java src/com/foo/Hello.java -d dist
----

Verify content

[tree]
--
#hello
##dist
###module-info.class
###com
####foo
#####Hello.class
--

3) Run

Add dist directory to the module path to be able to resolve *com.foo* module, and run *com.foo.Hello* class inside *com.foo* module.

[source,java]
----
java --module-path dist -m com.foo/com.foo.Hello
----

4) Package

We can package standard Java module as a JAR (Java Archive File).

[source,bash]
----
jar --create --file hello.jar --main-class=com.foo.Hello -C dist .
----

Verify that you have hello.jar file in the current directory.

////
5) Link

jlink is a link tool for Java 9. It creates a portable bundle of your application and JRE.

[source,bash]
----
jlink --module-path %JAVA_HOME%/jmods;hello.jar --add-modules com.foo --launcher hello=com.foo/com.foo.Hello --output release
----

After link, you have a special JRE which has Hello app. You can run it

[source,bash]
----
cd release
bin\hello.bat // for win
bin/hello // for *nix
----

////

*Practice 2*

Create different scale of JREs

[source,bash]
----
mkdir generate-image
cd generate-image

start jlink --module-path %JAVA_HOME%/jmods --add-modules java.base --output java.base
start jlink --module-path %JAVA_HOME%/jmods --add-modules java.se --output java.se
start jlink --module-path %JAVA_HOME%/jmods --add-modules java.se.ee --output java.se.ee
start jlink --module-path %JAVA_HOME%/jmods --add-modules java.desktop --output java.desktop
----

*Practice 3*

Using exports and requires keywords to control *access* between modules.

exports:: declares which package(s) are accessible from current module.
requires:: declares which module(s) are needed to read/access.


[width="100%",options="header",cols="1a,1a"]
|====================
| printer-client module | printer-impl module 
| 

[tree]
----
#printer-client
##src
###module-info.java
###com
####printer
#####client
######PrinterClient.java
----

| 

[tree]
----
#printer-impl
##src
###module-info.java
###com
####printer
#####impl
######Printer.java
----

|====================

1) When exports and requires are not declared

.Compile modules
[source,bash]
----
cd exports-requires-missed

javac \
printer-impl/module-info.java \
printer-impl/src/com/printer/impl/Printer.java \
-d dist/printer-impl

javac printer-client/module-info.java printer-client/src/com/printer/client/PrinterClient.java \
-p dist/printer-impl \
-d dist/printer-client
----

.Run modules
[source,bash]
----
java --module-path dist \
-m com.printer.client/com.printer.client.PrinterClient
----

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, but module com.printer.client does not read it)
1 error
////

2) When exports declared, but requires is not declared

[source,bash]
----
cd requires-missed
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, but module com.printer.client does not read it)
1 error
////

3) When requires declared, but exports is not declared

[source,bash]
----
cd exports-missed
----

////
printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, which does not export it)
1 error
////

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

4) When both requires and exports are declared

[source,bash]
----
cd exports-requires
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
Success
////

*Practice 4*

Auto-modules is designed for smooth migration to Java module system.

When a non-modular classic JAR file is added to module path (--module-path or -p), then it becomes an auto-module.

[TIP]
====
All packages of an auto-module are readable by other modules.
====

[source,bash]
----
cd auto-module
----

.Compile
[source,bash]
----
javac printer-impl/module-info.java printer-impl/src/com/printer/impl/Printer.java -p lib -d dist/printer-impl

javac printer-client/module-info.java printer-client/src/com/printer/client/PrinterClient.java -p dist/printer-impl;lib -d dist/printer-client
----

.Run
[source,bash]
----
java --module-path dist;lib  -m com.printer.client/com.printer.client.PrinterClient
----

*Practice 5*

If a module want to access to other module’s components, other module have to open or export required packages to caller module.

exports:: Makes packages accessible to other modules at compile time or run time.

opens:: Makes packages accessible to other modules only at run time including access to private members. 

[NOTE]
====
[source,java]
----
Class<?> clazz = Class.forName("com.printer.impl.Printer"); <1>
Class<Printer> clazz = Printer.class; <2>
----
<1> Access to the class at run-time
<2> Access to the class at compile time

====

1) Reflective acccess with exports (public method)

[source,bash]
----
cd module-reflection-exports
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
Hello world!
////

2) Reflective access with exports (private method)

[source,bash]
----
cd module-reflection-exports-private
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
Exception in thread "main" java.lang.reflect.InaccessibleObjectException: Unable to make private void com.printer.impl.Printer.print(java.lang.String) accessible: module com.printer.
impl does not "opens com.printer.impl" to module com.printer.client
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.checkCanSetAccessible(Unknown Source)
        at java.base/java.lang.reflect.Method.setAccessible(Unknown Source)
        at com.printer.client/com.printer.client.PrinterClient.main(PrinterClient.java:10)

////

3) Reflective access with opens (private method)

[source,bash]
----
cd module-reflection-opens-private
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
Hello world
////

3) 2) Non-Reflective access with opens (public method)

[source,bash]
----
cd module-reflection-opens-public
----

include::__STANDARD_PRINTER_COMPILE.adoc[]

include::__STANDARD_PRINTER_RUN.adoc[]

////
We get the error at compile time

printer-client\src\com\printer\client\PrinterClient.java:3: error: package com.printer.impl is not visible
import com.printer.impl.Printer;
                  ^
  (package com.printer.impl is declared in module com.printer.impl, which does not export it)
1 error
////

*Practice 6*

JShell

[source,bash]
----
jshell

|  Welcome to JShell -- Version 10.0.1
|  For an introduction type: /help intro
jshell>
jshell> 3 + 5 
jshell> /exit
----

[source,bash]
----
/env --add-modules jdk.incubator.httpclient
import jdk.incubator.http.*

var httpClient= HttpClient.newHttpClient()
var httpRequest= HttpRequest.newBuilder(URI.create("https://kodedu.com")).GET().build()
HttpResponse<String> httpResponse = httpClient.send(request, HttpResponse.BodyHandler.asString())
httpResponse.version()
httpResponse.statusCode()
httpResponse.body()
httpResponse.headers()
----
